---
mssql_repo_url: https://packages.microsoft.com/config/rhel/8/mssql-server-2022.repo
mssql_repo_name: mssql-server
mssql_pid: Developer
mssql_tcp_port: 1433
#mssql_sa_pwd: s3cr3t

mssql_tools_include: true
mssql_tools_repo_url: https://packages.microsoft.com/config/rhel/8/prod.repo
mssql_tools_repo_name: msprod
mssql_tools_users: []